version: '3.8'

services:
  backend:
    image: "moomin03/4thbackend:latest"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # 호스트의 static 디렉토리와 컨테이너의 static 디렉토리를 연결하여 결과물을 확인 가능하게 함
      - ./backend/static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    image: "moomin03/4thfrontend:latest"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # 프론트엔드 빌드 시 로컬 백엔드 API의 주소를 바라보도록 설정합니다.
        - PUBLIC_API_URL=http://localhost:8000
    ports:
      - "1234:80"
    depends_on:
      - backend
    restart: unless-stopped
